WebAppMain/Controllers/HallsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;
using WebAppMain.Data;
using WebAppMain.Models;


namespace WebAppMain.Controllers
{
    public class HallsController : Controller
    {
        private ApplicationDbContext db;
        public HallsController(ApplicationDbContext context)
        {
            db = context;
        }
        public async Task<ActionResult> ListHallsAsync()
        {
            var halls = await db.Halls
             .Include(c => c.Computers)
             .ToListAsync();
            return View(halls);
      
        }

        public IActionResult AddHalls()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AddHalls(Halls halls)
        {
            if (ModelState.IsValid)
            {
                db.Halls.Add(halls);
                await db.SaveChangesAsync();
                return RedirectToAction("ListHalls");
            }
            else
            {
                return View(halls);
            }
        }


        public async Task<IActionResult> EditHalls(int? id)
        {
            if (id != null)
            {
                Halls halls = await db.Halls.FirstOrDefaultAsync(p => p.HallsId == id);
                if (halls != null)
                    return View(halls);
            }
            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> EditHalls(Halls halls)
        {
            if (ModelState.IsValid)
            {
                db.Halls.Update(halls);
                await db.SaveChangesAsync();
                return RedirectToAction("ListHalls");
            }
            else
            {
                return View(halls);
            }
            
        } 
    

        

        [HttpGet]
        [ActionName("DeleteHalls")]
        public async Task<IActionResult> ConfirmDelete(int? id)
        {
            if (id != null)
            {
                Halls halls = await db.Halls.FirstOrDefaultAsync(p => p.HallsId == id);
                if (halls != null)
                    return View(halls);
            }
            return NotFound();
        }



        [HttpPost]
        public async Task<IActionResult> Delete(int? id)
        {
            
                Halls halls = await db.Halls
                    .Include(h => h.Visitings)
                    .FirstOrDefaultAsync(p => p.HallsId == id);

                if (halls != null)
                {
                    if (halls.Visitings.Count == 0)
                    {
                        db.Entry(halls).State = EntityState.Deleted;
                        await db.SaveChangesAsync();
                        return RedirectToAction("ListHalls");
                    }
                }
            

            return RedirectToAction("ListHalls");
        }

    }
}

WebAppMain/Controllers/UserController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using System.Threading.Tasks;
using WebAppMain.Data;
using WebAppMain.Models;



namespace WebAppMain.Controllers
{
    public class UserController : Controller
    {
        private ApplicationDbContext db;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
       

        public UserController(ApplicationDbContext context, UserManager<ApplicationUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            db = context;
            _roleManager = roleManager;
            _userManager = userManager;
        }


        [HttpGet]
        public async Task<IActionResult> ListUsers(string roleName, string searchString)
        {
            // get all users
            var users = _userManager.Users.ToList();
            
            if (!string.IsNullOrEmpty(roleName))
            {
                // get users in the specified role
                var usersInRole = await _userManager.GetUsersInRoleAsync(roleName);
                users = users.Intersect(usersInRole).ToList();
            }

          


            
           
            // pass the filtered list of users to the view
            return View(users);
        }



        [HttpPost]
        public async Task<IActionResult> EditUser(EditUserVM model)
        {
            var user = await _userManager.FindByIdAsync(model.Id);

            if (user == null)
            {
                ViewBag.ErrorMessage = $"Пользователь с идентификатором = {model.Id} не найден";
                return View("NotFound");
            }
            else
            {
                user.Email = model.Email;
                user.FirstName = model.FirstName;
                user.LastName = model.LastName;
                user.Patronymic = model.Patronymic;

                var result = await _userManager.UpdateAsync(user);

                if (result.Succeeded)
                {
                    return RedirectToAction("ListUsers");
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }

                return View(model);
            }
        }


        [HttpGet]
        public async Task<IActionResult> EditUser(string id)
        {
            var user = await _userManager.FindByIdAsync(id);

            if (user == null)
            {
                ViewBag.ErrorMessage = $"Пользователь с идентификатором =  {id}  не найден";
                return View("NotFound");
            }

            // GetClaimsAsync retunrs the list of user Claims
            var userClaims = await _userManager.GetClaimsAsync(user);
            // GetRolesAsync returns the list of user Roles
            var userRoles = await _userManager.GetRolesAsync(user);

            var model = new EditUserVM
            {
                Id = user.Id,
                Email = user.Email,
                FirstName = user.FirstName,
                LastName = user.LastName,
                PhoneNumber = user.PhoneNumber,

                Claims = userClaims.Select(c => c.Value).ToList(),
                Roles = userRoles
            };

            return View(model);


        }

        [HttpPost]
        public async Task<IActionResult> DeleteUser(string id)
        {

            var user = await _userManager.FindByIdAsync(id);

            if (user == null)
            {
                ViewBag.ErrorMessage = $"Пользователь с идентификатором =  {id}  не найден";
                return View("NotFound");
            }
            else
            {
                var roles = await _userManager.GetRolesAsync(user);
                if (roles.Contains("Admin"))
                {
                    ViewBag.ErrorMessage = $"Вы не можете удалить пользователя-администратора";
                    return RedirectToAction("ListUsers");
                }

                var result = await _userManager.DeleteAsync(user);

                if (result.Succeeded)
                {
                    return RedirectToAction("ListUsers");
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }

                return View("ListUsers");
            }
        
        }
    }
}

WebAppMain/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity;
@inject SignInManager<ApplicationUser> signInManager;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebAppMain</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/File.css" />
    <link rel="stylesheet" href="/css/fontawesome.css">
    <link rel="stylesheet" href="/css/templatemo-cyborg-gaming.css">
    <link rel="stylesheet" href="/css/owl.css">
    <link rel="stylesheet" href="/css/animate.css">
    <link rel="stylesheet" href="https://unpkg.com/swiper@7/swiper-bundle.min.css" />
    <link rel="stylesheet" href="~/css/style.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" />
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css%22%3E"/>
   


</head>
<body>
  
        <header class="header-area header-sticky">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <nav class="main-nav">
                            <!-- ***** Logo Start ***** -->
                        <a asp-controller="Home" asp-action="Index" class="logo">
                                <img src="../img/Logo.png" alt="">
                            </a>
                            <!-- ***** Logo End ***** -->
                            
                            <!-- ***** Menu Start ***** -->
                            <ul class="nav">
                            @if (signInManager.IsSignedIn(User) && User.IsInRole("Разработчик") || User.IsInRole("Администратор"))
                            {

                                <li>
                                    <a   asp-controller="Services" asp-action="ListServices">Услуги </a>
                                </li>
                                <li>
                                    <a   asp-controller="Computer" asp-action="ListComputer">Компьютеры </a>
                                </li>
                                <li>
                                    <a   asp-controller="Halls" asp-action="ListHalls">Залы </a>
                                </li>
                                <li>
                                    <a   asp-controller="Visitor" asp-action="ListVisitor">Посетители </a>
                                </li>
                                <li>
                                    <a   asp-controller="Visiting" asp-action="ListVisiting">Посещение </a>
                                </li>
                                <li>
                                    <a   asp-controller="UserRoles" asp-action="Index">Роли </a>
                                </li>
                                <li>
                                    <a   asp-controller="User" asp-action="ListUsers">Пользователи </a>
                                </li>

                            }
                            @if (signInManager.IsSignedIn(User) && User.IsInRole("Сотрудник"))
                            {
                                <li>
                                    <a   asp-controller="Services" asp-action="ListServices">Услуги </a>
                                </li>
                                <li>
                                    <a   asp-controller="Computer" asp-action="ListComputer">Компьютеры </a>
                                </li>
                                <li>
                                    <a   asp-controller="Halls" asp-action="ListHalls">Залы </a>
                                </li>
                                <li>
                                    <a   asp-controller="Visitor" asp-action="ListVisitor">Посетители </a>
                                </li>
                                <li>
                                    <a   asp-controller="Visiting" asp-action="ListVisiting">Посещение </a>
                                </li>
                            }
                            @if (signInManager.IsSignedIn(User) && User.IsInRole("Гость"))
                            {
                                <li>
                                    <a   asp-controller="Home" asp-action="AddVisitingGuest">запись </a>
                                </li>
                            }
                            @if (signInManager.IsSignedIn(User))
                            {
                                <li class="mt-1">
                                    <a asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage" alt=""> Профиль</a>
                                </li>
                               
                            }
                            else
                            {
                                <li>
                                    <a asp-area="Identity" asp-page="/Account/Register">Регистрация</a>
                                </li>
                                <li class="mt-1"\>
                                    <a asp-area="Identity" asp-page="/Account/Login">Авторизация</a>
                                </li>
                            }
                            </ul>
                           
                            <!-- ***** Menu End ***** -->
                        </nav>
                    </div>
                </div>
            </div>
       
 
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    </header>
    
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@2.9.3/dist/umd/popper.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>