WebAppMain/Models/Visitors.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace WebAppMain.Models
{
    public class Visitors
    {
        public int VisitorsId { get; set; }
        [Required(ErrorMessage = "Укажите имя")]
        public string Name { get; set; }

        public string Addres { get; set; }

        public string Constant { get; set; }

        public DateTime? DateOfBirth { get; set; }

        public Visiting Visiting { get; set; }
    }
}

WebAppMain/Controllers/VisitorController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;
using WebAppMain.Data;
using WebAppMain.Models;
using System.Linq;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Http;
using System.Data;
using System.IO;
using Microsoft.AspNetCore.Identity;

namespace WebAppMain.Controllers
{
    public class VisitorController : Controller
    {
        private ApplicationDbContext db;
        private readonly UserManager<ApplicationUser> _userManager;

        public VisitorController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            db = context;
            _userManager = userManager;

        }

  
        
        public IActionResult ListVisitor(string searchString, string constantFilter)
        {
            var visitors = db.Visitors.Include(v => v.Visiting).AsQueryable();


            if (!string.IsNullOrEmpty(searchString))
            {
                visitors = visitors.Where(v => v.Name.Contains(searchString));
            }


            if (!string.IsNullOrEmpty(constantFilter))
            {
                visitors = visitors.Where(v => v.Constant == constantFilter);
            }

            return View(visitors.ToList());
        }



        public IActionResult AddVisitor()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AddVisitor(Visitors visitor)
        {
            db.Visitors.Add(visitor);
            await db.SaveChangesAsync();
            return RedirectToAction("ListVisitor");
        }


        public async Task<IActionResult> EditVisitor(int? id)
        {
            if (id != null)
            {
                Visitors visitor = await db.Visitors.FirstOrDefaultAsync(p => p.VisitorsId == id);
                if (visitor != null)
                    return View(visitor);
            }
            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> EditVisitor(Visitors visitor)
        {
            db.Visitors.Update(visitor);
            await db.SaveChangesAsync();
            return RedirectToAction("ListVisitor");
        }

       

        [HttpGet]
        [ActionName("DeleteVisitor")]
        public async Task<IActionResult> ConfirmDelete(int? id)
        {
            if (id != null)
            {
                Visitors visitor = await db.Visitors.FirstOrDefaultAsync(p => p.VisitorsId == id);
                if (visitor != null)
                    return View(visitor);
            }
            return NotFound();
        }



        //[HttpPost]
        //public async Task<IActionResult> Delete(int? id)
        //{
           
        //        Visitors visitors = await db.Visitors
        //            .Include(h => h.Visiting)
        //            .FirstOrDefaultAsync(p => p.VisitorsId == id);

        //        if (visitors != null)
        //        {
        //            if (visitors.Visiting.Count == 0)
        //            {
        //                db.Entry(visitors).State = EntityState.Deleted;
        //                await db.SaveChangesAsync();
        //                return RedirectToAction("ListVisitor");
        //            }
        //        }
            

        //    return RedirectToAction("ListVisitor");
        //}

        [HttpPost]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id != null)
            {
                Visitors services = new Visitors { VisitorsId = id.Value };
                db.Entry(services).State = EntityState.Deleted;
                await db.SaveChangesAsync();
                return RedirectToAction("ListVisitor");
            }
            return NotFound();
        }
    }
}

WebAppMain/Views/Visitor/AddVisitor.cshtml
@model WebAppMain.Models.Visitors
@{
    ViewBag.Title = "Добавление посетителя";
}

<form asp-action="AddVisitor" asp-controller="Visitor">
    <div class="container ">
        <div class="card shadow roundeds mt-5" style="background: #27292a;">
            <div class="center-wrap m-4">
                <h4 class="text-lg-center" style="color: #ec6090;">Добавление посетителя</h4>
                <div class="form-group">
                    <label asp-for="Name" style="color: #ec6090;" class="control-label">ФИО</label>
                    <input type="text" asp-for="Name" placeholder="ФИО" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Addres" style="color: #ec6090;" class="control-label">Адрес</label>
                    <input type="text" asp-for="Addres" placeholder="Адрес" class="form-control" />
                    <span asp-validation-for="Addres" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Name" style="color: #ec6090;" class="control-label">Дата рождения</label>
                    <input type="date" asp-for="DateOfBirth" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Name" style="color: #ec6090;" class="control-label">Постоянный клиент</label>
                    <select class="form-control" asp-for="Constant">
                        <option value="">Выберите тип</option>
                        <option>Да</option>
                        <option>Нет</option>
                    </select>
                </div>
                <div class="form-group">
                    <button type="submit" style="background-color: #ec6090" class="btn btn-danger">Создать</button>
                    <a asp-action="ListVisitor" style="background-color: #ec6090" class="btn btn-danger">Отмена</a>
                </div>
            </div>
        </div>
    </div>
    </div>


</form>
@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

WebAppMain/Views/Visitor/EditVisitor.cshtml
@model WebAppMain.Models.Visitors
@{
    ViewBag.Title = "Редактирование посетителя";
}
<form asp-action="EditVisitor" asp-controller="Visitor" asp-route-VisitorsId="@Model.VisitorsId">
    <div class="container ">
        <div class="card shadow roundeds mt-5" style="background: #27292a;">
            <div class="center-wrap m-4">
                <h4 class="text-lg-center" style="color: #ec6090;">Редактирование посетителя</h4>
                <div class="form-group">
                    <label asp-for="Name" style="color: #ec6090;" class="control-label">ФИО</label>
                    <input type="text" asp-for="Name" placeholder="ФИО" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Addres" style="color: #ec6090;" class="control-label">Адрес</label>
                    <input type="text" asp-for="Addres" placeholder="Адрес" class="form-control" />
                    <span asp-validation-for="Addres" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Name" style="color: #ec6090;" class="control-label">Дата рождения</label>
                    <input type="date" asp-for="DateOfBirth" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Name" style="color: #ec6090;" class="control-label">Постоянный клиент</label>
                    <select class="form-control" asp-for="Constant">
                        <option value="">Выберите тип</option>
                        <option>Да</option>
                        <option>Нет</option>
                    </select>
                </div>
                <div class="form-group">
                    <button type="submit" style="background-color: #ec6090" class="btn ">Обновить</button>
                    <a asp-action="ListVisitor" style="background-color: #ec6090" class="btn btn-danger">Отмена</a>
                </div>
            </div>
        </div>
    </div>
   

</form>
@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

WebAppMain/Views/Visitor/ListVisitor.cshtml
@model IEnumerable<WebAppMain.Models.Visitors>
@{
    ViewBag.Title = "Все посетители";
}
<h1>Все посетители</h1>

<div class="main-button">
    <a asp-action="AddVisitor"
       style="width:auto">
        Добавить нового посетителя
    </a>
</div>
<div class="page-content p-5">
    <div class="most-popular mt-0">
        <div class="filter-search-container row align-items-center">         
            <div class=" search-container">
                <form method="get">
                    <div class="form-group w-100 mb-0 me-2">
                        <input style="background-color: #27292a; " type="text" name="searchString" class="form-control" placeholder="Поиск по имени" id="searchString" />
                    </div>
                    <button type="submit" class="btn-sm btn" style="color:white">
                        <i class="bi bi-search"></i>
                    </button>
                    <a href="#" id="clearSearch" class="btn-sm btn" style="color:white">
                        <i class="bi bi-x-square"></i>
                    </a>
                </form>
            </div>
        </div>
    </div>
</div>

  
<div class="card-tableNew">
    <table class="table table-borderless text-white">
        <thead>
            <tr style="color:#e75e8d">
                <th>ФИО</th>
                <th>Постоянный клиент</th>
                <th>Дата рожедния</th>
                <th>Интсрументы</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var visitor in Enumerable.Reverse(Model))
            {
                <tr class="accordion" data-toggle="collapse" data-target="#collapse@(visitor.VisitorsId)" aria-expanded="false" aria-controls="collapse@(visitor.VisitorsId)">
                    <td style="color:white">@visitor.Name</td>
                    <td style="color:white">@visitor.Constant</td>
                    <td style="color:white">@visitor.DateOfBirth?.ToString("dd.MM.yyyy")</td>
                   
                    <td>
                        <form asp-action="Delete" asp-route-id="@visitor.VisitorsId" method="post">
                            <a asp-action="EditVisitor" asp-controller="Visitor" asp-route-id="@visitor.VisitorsId" class="btn ">
                                <i class="mt-1 bx bx-edit-alt bx-xs" style="color:white"></i>
                            </a>
                            <button class="btn " onclick="return confirm('Вы уверены что хотите удалить данного пользователя: @visitor.Name')">

                                <i class='bi bi-trash3' style="color:white"></i>
                            </button>
                        </form>
                    </td>
                </tr>
                <tr>
                    <td colspan="3">
                        <div id="collapse@(visitor.VisitorsId)" class="collapse">
                            <p style="color:white">Адрес Проживания: @visitor.Addres</p>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
    @*<div class="card-tableNew">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>ФИО</th>
                    <th>Постоянный клиент</th>
                    <th>Дата рожедния</th>
                    <th>Интсрументы</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var visitor in Enumerable.Reverse(Model))
                {
                    <tr class="accordion" data-toggle="collapse" data-target="#collapse@(visitor.VisitorsId)" aria-expanded="false" aria-controls="collapse@(visitor.VisitorsId)">
                        <td>@visitor.Name</td>
                        <td>@visitor.Constant</td>
                        <td>@visitor.DateOfBirth?.ToString("dd.MM.yyyy")</td>
                        <td>
                           
                        </td>
                    </tr>
                    <tr>
                        <td colspan="3">
                            <div id="collapse@(visitor.VisitorsId)" class="collapse">
                                <p>Адрес Проживания: @visitor.Addres</p>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
}*@


@section Scripts {
    <script>
        document.addEventListener("DOMContentLoaded", function () {
            var accordions = document.getElementsByClassName("accordion");

            for (var i = 0; i < accordions.length; i++) {
                accordions[i].addEventListener("click", function () {
                    this.classList.toggle("active");

                    var panel = this.nextElementSibling;
                    if (panel.style.maxHeight) {
                        panel.style.maxHeight = null;
                    } else {
                        panel.style.maxHeight = panel.scrollHeight + "px";
                    }
                });
            }
        });
    </script>
}